language: python

python:
  - 3.5

services:
  - postgresql

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

git:
  depth: 3

env:
  global:
    - PG_DATABASE=postgres
    - MONTH=2017-05
    - DATE=2017-05-20
    - FEED=1

  matrix:
    - TASK=routeratio
    - TASK=spacing
    - TASK=evt
    - TASK=prepare cewt
    - TASK=otp
    - TASK=otd
    - TASK=prepare bunching
    - TASK=service
    - TASK=speed
    - TASK=prepare wtp

before_install:
  - psql --version
  - git clone https://github.com/fitnr/gtfs-sql-importer.git
  - git --git-dir gtfs-sql-importer/.git branch -v | grep master
  - git clone https://github.com/Bus-Data-NYC/mta-bus-archive.git
  - git --git-dir mta-bus-archive/.git branch -v | grep master
  - pip install -r mta-bus-archive/requirements.txt

install: 
  - make -e init drop_constraints -C gtfs-sql-importer
  - make -e init download -C mta-bus-archive
  - make -e init

before_script:
  - psql $PG_DATABASE -c "select postgis_full_version()"

script: make -e $TASK
